version: '3'
services:
  gateway:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=SmartCity/gateway/api_gateway.py
      - FLASK_ENV=development
      - SEMAFORO_URL=http://semaforo:5001/estado
      - ILUMINACAO_URL=http://iluminacao:5002/estado
    command: python -m flask run --host=0.0.0.0

  semaforo:
    build: .
    ports:
      - "5001:5001"
    command: python SmartCity/service/semaforo_service.py

  iluminacao:
    build: .
    ports:
      - "5002:5002"
    command: python SmartCity/service/iluminacao_service.py